import swaggerAutogen from "swagger-autogen";

const outputFile = "./src/config/swagger.json";
const endpointsFiles = ["./src/server.ts"];

const swagger = swaggerAutogen({ lang: "pt-br" });

const doc = {
    info: {
        version: "1.0.0",
        title: "Alpha Minion",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module.",
    },
    host: "localhost:8888",
    basePath: "/",
    schemes: ["http", "https"],
    consumes: ["application/json"],
    produces: ["application/json"],
    tags: [
        {
            name: "Users",
            description: "Endpoints to manage users",
        },
        {
            name: "People",
            description: "Endpoints to manage people",
        },
    ],
    definitions: {

        Error401: {
            errors: ["Não autorizado"],
            status: 401,
        },
        Error500: {
            errors: ["Erro interno do servidor"],
            status: 500,
        },
    },
};

swagger(outputFile, endpointsFiles, doc);
